# TCL File Generated by Component Editor 15.0
# Mon Jun 15 17:02:22 CDT 2015
# DO NOT MODIFY


# 
# OpenLDI_RX "OpenLDI_RX" v1.0
#  2015.06.15.17:02:22
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0
package require altera_terp


# 
# module OpenLDI_RX
# 
set_module_property DESCRIPTION ""
set_module_property NAME OpenLDI_RX
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME OpenLDI_RX
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property SUPPORTED_DEVICE_FAMILIES {{Stratix V} {Arria 10} {Arria V} {Arria V GZ} {Cyclone IV} {Cyclone IV E}  {Cyclone V} {MAX 10}}


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH generate
add_fileset SIM_VERILOG SIM_VERILOG generate
add_fileset SIM_VHDL SIM_VHDL generate


# 
# parameters
# 
# 
add_parameter "DEVICE_FAMILY" string "Stratix V"
set_parameter_property "DEVICE_FAMILY" HDL_PARAMETER true
set_parameter_property "DEVICE_FAMILY" DISPLAY_NAME "Device family"
set_parameter_property "DEVICE_FAMILY" ALLOWED_RANGES { "Arria 10" "MAX 10" "Stratix V" "Arria V" "Arria V GZ" "Cyclone V" "Cyclone IV E" "Cyclone IV GX" }
set_parameter_property "DEVICE_FAMILY" DESCRIPTION "Displays the device family"
set_parameter_property "DEVICE_FAMILY" AFFECTS_GENERATION true
set_parameter_property "DEVICE_FAMILY" ENABLED 0
add_display_item "Device Options" "DEVICE_FAMILY" PARAMETER 
set_parameter_property "DEVICE_FAMILY" SYSTEM_INFO {DEVICE_FAMILY}
set_parameter_property "DEVICE_FAMILY" HDL_PARAMETER false
add_parameter "DEVICE" string "Stratix V"
set_parameter_property "DEVICE" HDL_PARAMETER false
set_parameter_property "DEVICE" VISIBLE false
set_parameter_property "DEVICE" SYSTEM_INFO {DEVICE}
set_parameter_property "DEVICE" HDL_PARAMETER false
add_parameter G_DATA_RATE FLOAT 700.0
set_parameter_property G_DATA_RATE DEFAULT_VALUE 700.0
set_parameter_property G_DATA_RATE DISPLAY_NAME "Data Rate (Mbps)"
set_parameter_property G_DATA_RATE TYPE FLOAT
set_parameter_property G_DATA_RATE UNITS None
set_parameter_property G_DATA_RATE DESCRIPTION "Number of bits used per pixel (18 or 24 are the only legal values)"
set_parameter_property G_DATA_RATE HDL_PARAMETER false
add_parameter G_BITS_PER_PIXEL INTEGER 24
set_parameter_property G_BITS_PER_PIXEL DEFAULT_VALUE 24
set_parameter_property G_BITS_PER_PIXEL DISPLAY_NAME "Bits per Pixel"
set_parameter_property G_BITS_PER_PIXEL TYPE INTEGER
set_parameter_property G_BITS_PER_PIXEL UNITS None
set_parameter_property G_BITS_PER_PIXEL ALLOWED_RANGES {18 24}
set_parameter_property G_BITS_PER_PIXEL DESCRIPTION "Number of bits used per pixel (18 or 24 are the only legal values)"
set_parameter_property G_BITS_PER_PIXEL HDL_PARAMETER true
add_parameter GT_RGB_DWIDTH INTEGER 23
set_parameter_property GT_RGB_DWIDTH TYPE INTEGER
set_parameter_property GT_RGB_DWIDTH DERIVED true
set_parameter_property GT_RGB_DWIDTH HDL_PARAMETER false
set_parameter_property GT_RGB_DWIDTH VISIBLE false
add_parameter GT_RGB_DEWIDTH INTEGER 1
set_parameter_property GT_RGB_DEWIDTH TYPE INTEGER
set_parameter_property GT_RGB_DEWIDTH DERIVED true
set_parameter_property GT_RGB_DEWIDTH HDL_PARAMETER false
set_parameter_property GT_RGB_DEWIDTH VISIBLE false
add_parameter GT_JEIDA_MAP BOOLEAN true
set_parameter_property GT_JEIDA_MAP DISPLAY_NAME "Utilize JEIDA 24bpp data mapping"
set_parameter_property GT_JEIDA_MAP DESCRIPTION "The default is to utilize JEIDA data mapping, instead of SPWG/PSWG/VESA mapping for 24bpp mode."
add_parameter G_JEIDA_MAP STD_LOGIC 0
set_parameter_property G_JEIDA_MAP TYPE STD_LOGIC_VECTOR
set_parameter_property G_JEIDA_MAP DERIVED true
set_parameter_property G_JEIDA_MAP HDL_PARAMETER true
set_parameter_property G_JEIDA_MAP ALLOWED_RANGES 0:1
set_parameter_property G_JEIDA_MAP VISIBLE false
add_parameter GT_DUALPIXEL BOOLEAN false
set_parameter_property GT_DUALPIXEL DISPLAY_NAME "Utilize dual-pixel mode"
set_parameter_property GT_DUALPIXEL DESCRIPTION "Dual-pixel mode will utilize an 8 channel LVDS interface, instead of a 4 channel interface."
add_parameter G_DUALPIXEL INTEGER 0
set_parameter_property G_DUALPIXEL TYPE INTEGER
set_parameter_property G_DUALPIXEL DERIVED true
set_parameter_property G_DUALPIXEL HDL_PARAMETER true
set_parameter_property G_DUALPIXEL VISIBLE false
add_parameter GT_ALIGNMENT_VEC INTEGER 0
set_parameter_property GT_ALIGNMENT_VEC DEFAULT_VALUE 0
set_parameter_property GT_ALIGNMENT_VEC DISPLAY_NAME "Default bit slip"
set_parameter_property GT_ALIGNMENT_VEC TYPE INTEGER
set_parameter_property GT_ALIGNMENT_VEC UNITS None
set_parameter_property GT_ALIGNMENT_VEC ALLOWED_RANGES {0 1 2 3 4 5 6}
set_parameter_property GT_ALIGNMENT_VEC DESCRIPTION "Number of bits the LVDS interface should slip after configuration, in order to achieve byte alignment.  This should be a static amount for your system, depending on clock/data skew, and is not normally required to be adjusted."
set_parameter_property GT_ALIGNMENT_VEC HDL_PARAMETER false
add_parameter G_ALIGNMENT_VEC STD_LOGIC_VECTOR 0
set_parameter_property G_ALIGNMENT_VEC TYPE STD_LOGIC_VECTOR
set_parameter_property G_ALIGNMENT_VEC DERIVED true
set_parameter_property G_ALIGNMENT_VEC HDL_PARAMETER true
set_parameter_property G_ALIGNMENT_VEC ALLOWED_RANGES 0:79228162514264337593543950335
set_parameter_property G_ALIGNMENT_VEC VISIBLE false


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET reset Input 1


# 
# connection point RGB_clk
# 
add_interface RGB_clk clock start
set_interface_property RGB_clk associatedDirectClock ""
set_interface_property RGB_clk clockRate 0
set_interface_property RGB_clk clockRateKnown false
set_interface_property RGB_clk ENABLED true
set_interface_property RGB_clk EXPORT_OF ""
set_interface_property RGB_clk PORT_NAME_MAP ""
set_interface_property RGB_clk CMSIS_SVD_VARIABLES ""
set_interface_property RGB_clk SVD_ADDRESS_GROUP ""

add_interface_port RGB_clk RGB_PCLK_OUT clk Output 1


# 
# connection point RGB_data
# 
add_interface RGB_data conduit end
set_interface_property RGB_data ENABLED true
set_interface_property RGB_data EXPORT_OF ""
set_interface_property RGB_data PORT_NAME_MAP ""
set_interface_property RGB_data CMSIS_SVD_VARIABLES ""
set_interface_property RGB_data SVD_ADDRESS_GROUP ""

add_interface_port RGB_data RGB_PCLK vid_clk Output 1
add_interface_port RGB_data RGB_DATA vid_data Output GT_RGB_DWIDTH
add_interface_port RGB_data RGB_DE vid_de Output GT_RGB_DEWIDTH
add_interface_port RGB_data RGB_HSYNC vid_h_sync Output GT_RGB_DEWIDTH
add_interface_port RGB_data RGB_VSYNC vid_v_sync Output GT_RGB_DEWIDTH
add_interface_port RGB_data RGB_DVALID vid_datavalid Output 1
add_interface_port RGB_data RGB_LOCKED vid_locked Output 1
add_interface_port RGB_data RGB_F vid_f Output GT_RGB_DEWIDTH
add_interface_port RGB_data RGB_STD vid_std Output 1
add_interface_port RGB_data RGB_COLORENCODE vid_color_encoding Output 8
add_interface_port RGB_data RGB_BITWIDTH vid_bit_width Output 8
add_interface_port RGB_data RGB_SOF sof Input 1
add_interface_port RGB_data RGB_SOFLOCK sof_locked Input 1
add_interface_port RGB_data RGB_REFCLKDIV refclk_div Input 1
add_interface_port RGB_data RGB_OVERFLOW overflow Input 1


# 
# connection point LDI_misc
# 
add_interface LDI_misc conduit end
set_interface_property LDI_misc associatedClock RGB_clk
set_interface_property LDI_misc associatedReset reset
set_interface_property LDI_misc ENABLED true
set_interface_property LDI_misc EXPORT_OF ""
set_interface_property LDI_misc PORT_NAME_MAP ""
set_interface_property LDI_misc CMSIS_SVD_VARIABLES ""
set_interface_property LDI_misc SVD_ADDRESS_GROUP ""

add_interface_port LDI_misc LDIPLL_LOCKED pll_locked Output 1
add_interface_port LDI_misc SLIP_ALGNR slip Input "(G_DUALPIXEL+1)*G_BITS_PER_PIXEL/6"
add_interface_port LDI_misc SLIP_ACK slip_ack Output "(G_DUALPIXEL+1)*G_BITS_PER_PIXEL/6"


# 
# connection point LDI_clk
# 
add_interface LDI_clk clock end
set_interface_property LDI_clk clockRate 0
set_interface_property LDI_clk ENABLED true
set_interface_property LDI_clk EXPORT_OF ""
set_interface_property LDI_clk PORT_NAME_MAP ""
set_interface_property LDI_clk CMSIS_SVD_VARIABLES ""
set_interface_property LDI_clk SVD_ADDRESS_GROUP ""

add_interface_port LDI_clk LDI_CLK_IN clk Input 1


# 
# connection point LDI_data
# 
add_interface LDI_data conduit end
set_interface_property LDI_data associatedClock LDI_clk
set_interface_property LDI_data associatedReset reset
set_interface_property LDI_data ENABLED true
set_interface_property LDI_data EXPORT_OF ""
set_interface_property LDI_data PORT_NAME_MAP ""
set_interface_property LDI_data CMSIS_SVD_VARIABLES ""
set_interface_property LDI_data SVD_ADDRESS_GROUP ""

add_interface_port LDI_data LDI_DATA_IN ldi_data Input "(G_DUALPIXEL+1)*G_BITS_PER_PIXEL/6"

#
# "Generate" callback routine:
#   This process creates the top-level OpenLDI IP block and adds it as well as all sub-blocks to
#     the project.  It also invokes the MegaWizard to create the RX LVDS IP for older device families.
#
proc generate { entity_name } {
  # Set the variables that will be used to parameterize the RX LVDS IP blocks
  set DEVICE_FAMILY   [ get_parameter_value DEVICE_FAMILY ]
  set P_DATARATE [format "%.2f" [ get_parameter_value G_DATA_RATE ] ]
  set P_CLKFREQ  [format "%.6f" [expr {[get_parameter_value G_DATA_RATE] / 7.0 } ] ]
  set P_CLKPERIOD  [format "%.3f" [expr {7000.0 / [get_parameter_value G_DATA_RATE] } ] ]
  set P_NUMCHAN [expr ([get_parameter_value G_DUALPIXEL] + 1) * ([get_parameter_value G_BITS_PER_PIXEL] / 6)]
  # Define the terp file name
  set terp_path "OpenLDI_RX.vhd.terp"
  # Open the terp file for reading
  set terp_fd [open $terp_path]
  # Read the contents of the file
  set terp_contents [read $terp_fd]
  # Fetch the auto-generated entity name for the RXLDI_LVDS
  if {[expr {"$DEVICE_FAMILY" == "Cyclone IV E"} || {"$DEVICE_FAMILY" == "Cyclone IV GX"} \
         || {"$DEVICE_FAMILY" == "Cyclone V"}    || {"$DEVICE_FAMILY" == "Arria V"} \
         || {"$DEVICE_FAMILY" == "Stratix V"} ]} {
    set autogen_rxldilvds ${entity_name}_RXLDI_LVDS
  } else {
    set autogen_rxldilvds [get_instance_property RXLDI_LVDS HDLINSTANCE_GET_GENERATED_NAME]
  }
  # Set various parameter variables, which will be substituted in the terp file
  set terp_params(substitute_entity_name) $entity_name
  set terp_params(substitute_lvds_entity_name) ${autogen_rxldilvds}
  set terp_params(device_family) $DEVICE_FAMILY
  set terp_params(width_serial) [expr { $P_NUMCHAN - 1}]
  set terp_params(width_parallel) [expr { $P_NUMCHAN * 7 - 1}]
  # Generate the top-level HDL file from the terp file
  set top_file_contents [altera_terp $terp_contents terp_params]
  # Add the generated top-level HDL file, as well as any other sub-blocks to the
  #   fileset for the RX OpenLDI IP
  add_fileset_file ${entity_name}.vhd VHDL TEXT $top_file_contents
  add_fileset_file openldi2rgb.vhd VHDL PATH openldi2rgb.vhd
  add_fileset_file Des_Align_SM.vhd VHDL PATH Des_Align_SM.vhd

  # If we are generating for an older device family, we need to use the MegaWizard flow to
  #   generate the RX LVDS block.  Newer deivces utilize the "add_hdl_instance" flow in the
  #   "elaborate" callback routine
  if {[expr {"$DEVICE_FAMILY" == "Cyclone IV E"} || {"$DEVICE_FAMILY" == "Cyclone IV GX"} \
         || {"$DEVICE_FAMILY" == "Cyclone V"}    || {"$DEVICE_FAMILY" == "Arria V"} \
         || {"$DEVICE_FAMILY" == "Stratix V"} ]} {
    # Truncate precision of input clock frequency for Cyclone IV families
    if {[expr {"$DEVICE_FAMILY" == "Cyclone IV E"} || {"$DEVICE_FAMILY" == "Cyclone IV GX"} ]} {
      set P_CLKFREQ  [format "%.2f" [expr {[get_parameter_value G_DATA_RATE] / 7.0 } ] ] }
    # Define the terp file name
    set terp_path "RXLDI_LVDS.vhd.terp"
    # Open the terp file for reading
    set terp_fd [open $terp_path]
    # Read the contents of the file
    set terp_contents [read $terp_fd]
    # Set various parameter variables, which will be substituted in the terp file
    set terp_params(device_family) $DEVICE_FAMILY
    set terp_params(data_rate) $P_DATARATE
    set terp_params(clk_freq) $P_CLKFREQ
    set terp_params(clk_period) $P_CLKPERIOD
    set terp_params(num_channels) $P_NUMCHAN
    # Create a file descriptor to a temporary file that will contain the parameters used by the MegaWizard.
    set terp_output_dir [create_temp_file ""]
    set top_level_file_path [file join $terp_output_dir "${entity_name}_RXLDI_LVDS.vhd"]
    set f_handle [open $top_level_file_path w+]
    # Generate the MegaWizard parameterization file from the terp file, and store the data to a variable
    set top_file_contents [altera_terp $terp_contents terp_params]
    # Write out the stored file data (from the above variable) to our temp file
    puts $f_handle $top_file_contents
    close $f_handle
    # Use the MegaWizard to read in the parameter file, and regenerate the complete IP file.
    exec qmegawiz -silent OPTIONAL_FILES=NONE $top_level_file_path
    # Add the IP file generated above to the fileset for the RX OpenLDI IP
    add_fileset_file ${entity_name}_RXLDI_LVDS.vhd VHDL PATH $top_level_file_path
  }
}

#
# "Elaborate" callback routine:
#   This process sets some of the derived variables used to parameterize the IP.  It also creates the
#     RX LVDS IP for 10-series and newer device families.
#
proc elaborate {} {
  if {[ get_parameter_value GT_JEIDA_MAP ] } {
    set_parameter_value G_JEIDA_MAP 1
  } else {
    set_parameter_value G_JEIDA_MAP 0
  }
  if {[ get_parameter_value GT_DUALPIXEL ] } {
    set_parameter_value G_DUALPIXEL 1
    set_parameter_value GT_RGB_DWIDTH [expr [get_parameter_value G_BITS_PER_PIXEL] * 2 ]
    set_parameter_value GT_RGB_DEWIDTH 2
  } else {
    set_parameter_value G_DUALPIXEL 0
    set_parameter_value GT_RGB_DWIDTH [get_parameter_value G_BITS_PER_PIXEL]
    set_parameter_value GT_RGB_DEWIDTH 1
  }
  set P_NUMCHAN [expr ([get_parameter_value G_DUALPIXEL] + 1) * ([get_parameter_value G_BITS_PER_PIXEL] / 6)]
  # This block creates the alignment vector, used to slip the RX deserializer to the default bit alignment.
  if {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "1" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {2**84 + 2**72 + 2**60 + 2**48 + 2**36 + 2**24 + 2**12 + 1}]
  } elseif {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "2" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {5*2**84 + 5*2**72 + 5*2**60 + 5*2**48 + 5*2**36 + 5*2**24 + 5*2**12 + 5}]
  } elseif {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "3" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {21*2**84 + 21*2**72 + 21*2**60 + 21*2**48 + 21*2**36 + 21*2**24 + 21*2**12 + 21}]
  } elseif {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "4" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {85*2**84 + 85*2**72 + 85*2**60 + 85*2**48 + 85*2**36 + 85*2**24 + 85*2**12 + 85}]
  } elseif {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "5" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {341*2**84 + 341*2**72 + 341*2**60 + 341*2**48 + 341*2**36 + 341*2**24 + 341*2**12 + 341}]
  } elseif {[ get_parameter_value GT_ALIGNMENT_VEC ]  == "6" } {
    set_parameter_value G_ALIGNMENT_VEC [expr {1365*2**84 + 1365*2**72 + 1365*2**60 + 1365*2**48 + 1365*2**36 + 1365*2**24 + 1365*2**12 + 1365}]
  } else {
    set_parameter_value G_ALIGNMENT_VEC "0"
  }
  #
  # This block generates the RX LVDS IP.
  #
  set DEVICE_FAMILY   [ get_parameter_value DEVICE_FAMILY ]
  # Create the "Altera LVDS SerDes" IP, if we are targeting an Arria 10 device
  if {[ get_parameter_value DEVICE_FAMILY ]  == "Arria 10" } {
    set P_DATARATE [format "%.1f" [ get_parameter_value G_DATA_RATE ] ]
    set P_CLKFREQ  [format "%.8f" [expr [get_parameter_value G_DATA_RATE] / 7.0 ]]
    add_hdl_instance RXLDI_LVDS altera_lvds
    #set_instance_parameter_value RXLDI_LVDS ENABLE_MIGRATABLE_PORT_MAPPINGS "true"
    set_instance_parameter_value RXLDI_LVDS GENERATE_SDC_FILE "true"
    set_instance_parameter_value RXLDI_LVDS MODE "RX_Non-DPA"
    set_instance_parameter_value RXLDI_LVDS RX_INCLOCK_PHASE_SHIFT "0"
    set_instance_parameter_value RXLDI_LVDS NUM_CHANNELS "${P_NUMCHAN}"
    set_instance_parameter_value RXLDI_LVDS DATA_RATE "${P_DATARATE}"
    set_instance_parameter_value RXLDI_LVDS J_FACTOR "7"
    set_instance_parameter_value RXLDI_LVDS INCLOCK_FREQUENCY "${P_CLKFREQ}"
    set_instance_parameter_value RXLDI_LVDS RX_USE_BITSLIP "true"
    set_instance_parameter_value RXLDI_LVDS SYS_INFO_DEVICE [get_parameter_value DEVICE]
    set_instance_parameter_value RXLDI_LVDS SYS_INFO_DEVICE_FAMILY [get_parameter_value DEVICE_FAMILY]
    set_instance_property RXLDI_LVDS HDLINSTANCE_USE_GENERATED_NAME 1
  # Create the "Altera Soft LVDS" IP, if we are targeting a Max 10 device
  } elseif {[ get_parameter_value DEVICE_FAMILY ]  == "MAX 10" } {
    set P_DATARATE [format "%.2f" [ get_parameter_value G_DATA_RATE ] ]
    set P_CLKFREQ  [format "%.2f" [expr [get_parameter_value G_DATA_RATE] / 7.0 ]]
    add_hdl_instance RXLDI_LVDS altera_soft_lvds
    set_instance_parameter_value RXLDI_LVDS FUNCTIONAL_MODE "RX"
    set_instance_parameter_value RXLDI_LVDS NUMBER_OF_CHANNELS "${P_NUMCHAN}"
    set_instance_parameter_value RXLDI_LVDS DESERIALIZATION_FACTOR "7"
    set_instance_parameter_value RXLDI_LVDS INPUT_DATA_RATE "${P_DATARATE}"
    set_instance_parameter_value RXLDI_LVDS VALID_FREQ "${P_CLKFREQ}"
    set_instance_parameter_value RXLDI_LVDS ENABLE_RX_LOCKED_PORT_UI "true"
    set_instance_parameter_value RXLDI_LVDS COMMON_RX_TX_PLL_UI "true"
    set_instance_parameter_value RXLDI_LVDS PLL_SELF_RESET_ON_LOSS_LOCK_UI "true"
    set_instance_parameter_value RXLDI_LVDS PORT_RX_DATA_ALIGN_UI "true"
    set_instance_parameter_value RXLDI_LVDS PORT_RX_CHANNEL_DATA_ALIGN_UI "true"
    set_instance_parameter_value RXLDI_LVDS DATA_ALIGN_ROLLOVER "7"
    set_instance_property RXLDI_LVDS HDLINSTANCE_USE_GENERATED_NAME 1
  } 
}
